name: Generate ICS from Roster

on:
  push:
    paths:
      - roster.txt
      - shifts.json
      - generate_ics.py
      - requirements.txt

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate ICS
        run: python generate_ics.py

      - name: Commit ICS File
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add calendar.ics
          git commit -m "Update calendar.ics from roster" || echo "No changes to commit"
          git push
